### ISSUE TITLE
Audio and Microphone not working on Lenovo 500e Chromebook

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [eupnea-linux/audio-scripts#41]
- Apollo Lake
- robo360
- POP!_ OS Installed on USB stick 

I ran `setup-audio` and selected `sof` and rebooted. The audio still does work.

**Comment by ChocolateLoverRaj** [comment]
Should I try it with a different OS like Ubuntu?

**Comment by ChocolateLoverRaj** [comment]
I was able to fix the audio using https://www.reddit.com/r/chrultrabook/comments/uc0b6i/howto_audio_on_apollolake_devices_under_linux/?sort=new and then change the scaling using https://askubuntu.com/questions/910638/change-how-the-volume-scales-the-loudness-of-the-sound-at-100-volume in a Lubuntu os installed using [chrx](https://github.com/reynhout/chrx). Idk if the same solutions work with Depthboot.

**Comment by WeirdTreeThing** [comment]
The audio script already does all of that.

**Comment by ChocolateLoverRaj** [comment]
I tried doing https://github.com/eupnea-linux/audio-scripts/issues/41#issuecomment-1478934265 with Depthboot Ubuntu, but it didn't work. I think https://github.com/eupnea-linux/audio-scripts/issues/41#issuecomment-1478934265 only works with older kernel versions.

**Comment by ChocolateLoverRaj** [comment]
Update: After doing https://github.com/eupnea-linux/audio-scripts/issues/41#issuecomment-1478934265 I installed `pavucontrol` and then I went to configuration and selected "Pro Audio" and now it works with scaling!
![image](https://user-images.githubusercontent.com/52586855/227063382-50d90276-8fa6-4375-b69f-3841d73d2b84.png)
Idk if it was necesary to follow https://github.com/eupnea-linux/audio-scripts/issues/41#issuecomment-1478934265 or if `setup-audio` is what actually set it up.

**Comment by WeirdTreeThing** [comment]
Well I guess it is fixed now.

**Comment by ChocolateLoverRaj** [comment]
> Well I guess it is fixed now.

Actually it's fixed on my chromebook because I followed https://www.reddit.com/r/chrultrabook/comments/11y94gd/how_do_i_make_sound_work_on_my_chromebook_hp_11a/. It's not actually fixed in Eupnea / Depthboot.

**Comment by WeirdTreeThing** [comment]
> > Well I guess it is fixed now.
> 
> Actually it's fixed on my chromebook because I followed https://www.reddit.com/r/chrultrabook/comments/11y94gd/how_do_i_make_sound_work_on_my_chromebook_hp_11a/. It's not actually fixed in Eupnea / Depthboot.

Not only is that for stoneyridge, they never solved anything in that thread.

**Comment by ChocolateLoverRaj** [comment]
Sorry i sent the wrong link. I actually followed this guide: https://www.reddit.com/r/chrultrabook/comments/uc0b6i/howto_audio_on_apollolake_devices_under_linux/

**Comment by WeirdTreeThing** [comment]
It should work with the script now.

**Comment by ChocolateLoverRaj** [comment]
I just tried it today with a new os and updated packages and selected sof and it didn't work. I'll try it with avs and see if that works.

**Comment by ChocolateLoverRaj** [comment]
I tried it with avs and the headphones and headphone mic worked. The laptop mic didn't work, or it only worked while the headphones were plugged in.

**Comment by WeirdTreeThing** [comment]
I tried sof on my apl device and all I got was static from the speakers so I guess it is more broken than I initially thought.

**Comment by ChocolateLoverRaj** [comment]
> I tried sof on my apl device and all I got was static from the speakers so I guess it is more broken than I initially thought.

So should this issue be open?
